export const ADMIN_LOGIN_REQUEST = '@admin/LOGIN_REQUEST'
export const ADMIN_LOGIN_SUCCESS = '@admin/LOGIN_SUCCESS'
export const ADMIN_LOGIN_FAILURE = '@admin/LOGIN_FAILURE'
export const ADMIN_LOGOUT_SUCCESS = '@admin/LOGOUT_SUCCESS'
