export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST'
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS'
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE'
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS'

export const GET_MEMBERS_REQUEST = 'GET_MEMBERS_REQUEST'
export const GET_MEMBERS_SUCCESS = 'GET_MEMBERS_SUCCESS'
export const GET_MEMBERS_FAILURE = 'GET_MEMBERS_FAILURE'

export const GET_SALES_REQUEST = 'GET_SALES_REQUEST'
export const GET_SALES_SUCCESS = 'GET_SALES_SUCCESS'
export const GET_SALES_FAILURE = 'GET_SALES_FAILURE'
