export const ADMIN_LOGIN_REQUEST = '@admin/LOGIN_REQUEST'
export const ADMIN_LOGIN_SUCCESS = '@admin/LOGIN_SUCCESS'
export const ADMIN_LOGIN_FAILURE = '@admin/LOGIN_FAILURE'
export const ADMIN_LOGOUT_SUCCESS = '@admin/LOGOUT_SUCCESS'

export const GET_MEMBERS_REQUEST = '@GET_MEMBERS_REQUEST'
export const GET_MEMBERS_SUCCESS = '@GET_MEMBERS_SUCCESS'
export const GET_MEMBERS_FAILURE = '@GET_MEMBERS_FAILURE'

export const GET_SALES_REQUEST = '@GET_SALES_REQUEST'
export const GET_SALES_SUCCESS = '@GET_SALES_SUCCESS'
export const GET_SALES_FAILURE = '@GET_SALES_FAILURE'
